version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
  frontend:
    build: frontend
    ports:
      - 80:3000
    depends_on:
      - api
  api:
    build: api
    ports:
      - 5000:8080
    volumes:
      - ./api:/code
    command: ["waitress-serve", "autoapp:app"]
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - HASHIDS_SALT=${HASHIDS_SALT}
      - FRONTEND_APP_URL=${FRONTEND_APP_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8081:8081
