version: "3.9"
services:
  web:
    build: api 
    ports:
      - "5000:8080"
    volumes:
      - ./api:/code
    command: ["pipenv", "run", "flask", "run", "--host", "0.0.0.0", "--port", "8080"]
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
  redis:
    image: "redis:alpine"
